"use strict";

import * as Kafka from "./kafka/Kafka";  // TODO: ...
import * as Drainer from "./kafka/Drainer";  // TODO: ...
import * as Publisher from "./kafka/Publisher";  // TODO: ...
import * as PartitionDrainer from "./kafka/PartitionDrainer";  // TODO: ...

import * as Consumer from "./connect/Consumer";  // TODO: ...
import * as Producer from "./connect/Producer";  // TODO: ...

import * as NConsumer from "./librdkafka/NConsumer";  // TODO: ...
import * as NProducer from "./librdkafka/NProducer";  // TODO: ...

import * as Health from "./librdkafka/Health";  // TODO: ...
import * as Analytics from "./librdkafka/Analytics";  // TODO: ...

export = {
  Kafka,
  Drainer,
  PartitionDrainer,
  Publisher,
  Consumer,
  Producer,
  NConsumer,
  NProducer,
  Health,
  Analytics
};
